### PR TITLE
virtio terminal: Use Test::Warnings

### PR DESCRIPTION
**Pull request by richiejp**
Remove custom code to catch warnings and use Test::Warnings instead.

### CODE REVIEW

**Comment by okurz** [comment]
does not seem to work for me. It fails because some parts of the test seem to finish after "done_testing()" ?!?

**Comment by richiejp** [comment]
Hopefully it will be more robust now.

**Comment by okurz** [comment]
```
$ prove t/10-terminal.t
t/10-terminal.t .. Failed -10/8 subtests 

Test Summary Report
-------------------
t/10-terminal.t (Wstat: 0 Tests: 24 Failed: 6)
  Failed tests:  1-5, 11
  Parse errors: Tests out of sequence.  Found (1) but expected (3)
                Tests out of sequence.  Found (3) but expected (4)
                Tests out of sequence.  Found (2) but expected (5)
                Tests out of sequence.  Found (4) but expected (6)
                Tests out of sequence.  Found (3) but expected (7)
Displayed the first 5 of 26 TAP syntax errors.
Re-run prove with the -p option to see them all.
Files=1, Tests=24,  2 wallclock secs ( 0.02 usr  0.00 sys +  1.16 cusr  0.11 csys =  1.29 CPU)
Result: FAIL
```

what does it tell for you? :-)

**Comment by richiejp** [comment]
The test framework we are using doesn't support forking out of the box. So I just reset the test object after forking and then we get repeat test numbers in the wrong order from the point of view of TAP. I'm not sure we would get enough value from fixing it, especially as we don't declare the number of tests at the beginning.

Fennec supports forking out of the box and is possibly just a better tests suite anyway (looks more declarative), but I think switching to that is a backlog entry at best.

**Comment by okurz** [comment]
On Friday, 17 February 2017 00:41:05 CET Richard Palethorpe wrote:
> The test framework we are using doesn't support forking out of the box. So I
> just reset the test object after forking and then we get repeat test
> numbers in the wrong order from the point of view of TAP. I'm not sure we
> would get enough value from fixing it, especially as we don't declare the
> number of tests at the beginning.
>
> Fennec supports forking out of the box and is possibly just a better tests
> suite anyway (looks more declarative), but I think switching to that is a
> backlog entry at best.

cool idea. I just took a first glimpse. Looks good to me. perl-Fennec-Lite is 
in Leap as well and it looks like a straightforward drop-in replacement. I 
suggest you try it out and see if you can fix it even faster then.

My intention is at first to prevent uncatched regressions by ensuring not more 
warnings show up in tests. I hope the easiest way to handle this is to fix the 
remaining warnings and just not accept any. If that is not feasible then 
explicitly handle and accept the warnings which can not be prevented and make 
sure the tests pass.

**Comment by richiejp** [comment]
Fennec-Lite doesn't have the forking stuff (result capturing), so it would have to be full Fennec. I don't know how it would effect the warnings package. My test doesn't produce any warnings though and if it did the warnings package would detect it, so that problem is fixed with this PR.

Getting my test to produce valid TAP results is another matter.

**Pull request closed without merging**
